CREATE VIEW [dbo].[vwRematricula]
	AS SELECT 
		[REMATRICULA].[CODIGO] RematriculaId,
		[DT_REMATRICULA] DataRematricula,
		[COD_USUARIO] UsuarioId,
		[COD_ENSINO_ALUNO] MatriculaId,
		[COD_ENSINO] TipoEnsinoId
	FROM
		REMATRICULA JOIN ENSINO_ALUNO ON REMATRICULA.COD_ENSINO_ALUNO = ENSINO_ALUNO.CODIGO
